# Generated by Django 5.1.6 on 2025-03-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("square_footage", models.IntegerField()),
                ("property_type", models.CharField(max_length=50)),
                (
                    "image_path",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images/"
                    ),
                ),
            ],
        ),
    ]
